replace copy with submodule
Lightning-Universe/ICML22-BLIP-research-poster pull request #17
Opened 2023-02-16 15:57 UTC by Borda

## What does this PR do?

let's do not duplicate code...

## Did you have fun?

Make sure you had fun coding 🙃

2023-02-16 16:35 UTC, aniketmaurya approved these changes

2023-02-16 16:37 UTC, aniketmaurya requested changes
the submodule is modified and contains `gradio_app.py` which implements model demo

2023-02-16 16:46 UTC, Borda commented
@aniketmaurya moved this file to root and will put it yo the right place after in #16

2023-02-20 15:42 UTC, aniketmaurya approved these changes

2023-02-20 15:47 UTC, merged